### ISSUE TITLE
关于resdata.json

### ISSUE THREAD

**Issue by size404zzz** [gf-data-tools/gf-resource-downloader#2]
求教resdata是如何获取的，同理的方法，是不是也可以用于云图和追放的资源下载

**Comment by ZeroRin** [comment]
打开游戏的时候就会自动下载文件列表了，然后unity解一下就能拿到这个文件。因为之前打包exe的时候UnityPy遇到一些奇怪的情况打不上，所以没有在这个软件里直接下载文件而是通过放在GitHub上的[其他repo](https://github.com/gf-data-tools/gfl-data-miner-python)里的定时action完成的
不玩追放和云图，不熟。

**Comment by size404zzz** [comment]
感谢大佬解答！
